# Generated by Django 5.1.3 on 2024-11-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymstore', '0004_alter_cartitem_cart_alter_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
