# Generated by Django 5.1.3 on 2024-11-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymstore', '0006_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product'),
        ),
    ]
